FROM python:3.8-slim
WORKDIR /app

RUN apt-get update && \
    apt-get install -y build-essential gcc g++ gfortran libopenblas-dev liblapack-dev && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip setuptools wheel
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8501
CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
